### ISSUE TITLE
grokview.view warn method in testing raises false positive deprecation warnings. 

### ISSUE THREAD

**Issue by tisto** [zopefoundation/grokcore.view#1]
The warn method has been added in 2008 saying "When zope.deprecation is fixed, this warn function can be removed again.":

https://github.com/zopefoundation/grokcore.view/blame/master/src/grokcore/view/testing.py#L35

I guess the method is now just outdated and therefore raises false warnings. Would it be ok to just remove the method?

**Comment by janwijbrand** [comment]
One of the tests did not properly "undo" the monkey patch of `warnings.warn`. I fixed. The tests pass again now, without false positive.
