### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/grokcore.view#14]
I'd like to cut a release of this package but I do not have the necessary PyPI rights.

@janwijbrand @janjaapdriessen @reinout @thefunny42 you are owners of this PyPI project.
Could one of you please add me (`icemac`) to that list, too?

**Comment by janwijbrand** [comment]
I added you just now

**Comment by icemac** [comment]
@janwijbrand Thank you, I just released https://pypi.org/project/grokcore.view/3.2/.
